require("dotenv").config();
const db = require("./models");

const SEED_DATA = async () => {
  // 1. Roles
  const [adminRole] = await db.role.findOrCreate({
    where: { roleName: "admin" },
    defaults: { description: "Full system access" },
  });
  const [managerRole] = await db.role.findOrCreate({
    where: { roleName: "manager" },
    defaults: { description: "Department level access" },
  });
  const [userRole] = await db.role.findOrCreate({
    where: { roleName: "user" },
    defaults: { description: "Basic access" },
  });
  const [guestRole] = await db.role.findOrCreate({
    where: { roleName: "guest" },
    defaults: { description: "Read-only access" },
  });

  // 2. Users
  const [alice] = await db.user.findOrCreate({
    where: { email: "alice@example.com" },
    defaults: {
      name: "Alice Smith",
      username: "alicesmith",
      password: "hashed_password",
      phoneNumber: "1234567890",
      emailVerified: true,
      acceptedTerms: true,
    },
  });
  const [bob] = await db.user.findOrCreate({
    where: { email: "bob@example.com" },
    defaults: {
      name: "Bob Johnson",
      username: "bobjohnson",
      password: "hashed_password",
      phoneNumber: "0987654321",
      emailVerified: false,
      acceptedTerms: true,
    },
  });
  const [charlie] = await db.user.findOrCreate({
    where: { email: "charlie@example.com" },
    defaults: {
      name: "Charlie Brown",
      username: "charliebrown",
      password: "hashed_password",
      phoneNumber: "5551234567",
      emailVerified: true,
      acceptedTerms: true,
    },
  });
  const [diana] = await db.user.findOrCreate({
    where: { email: "diana@example.com" },
    defaults: {
      name: "Diana Prince",
      username: "dianaprince",
      password: "hashed_password",
      emailVerified: true,
      acceptedTerms: true,
    },
  });

  // 3. UserRoles
  await alice.addRoles([adminRole, userRole]);
  await bob.addRoles([managerRole]);
  await charlie.addRoles([userRole]);
  await diana.addRoles([guestRole]);

  // 4. Sessions (Active & Expired)
  const yesterday = new Date();
  yesterday.setDate(yesterday.getDate() - 1);

  const tomorrow = new Date();
  tomorrow.setDate(tomorrow.getDate() + 1);

  await db.session.findOrCreate({
    where: { token: "token_alice_1" },
    defaults: { flag: true, expiresAt: tomorrow, userId: alice.id },
  });
  await db.session.findOrCreate({
    where: { token: "token_alice_2" },
    defaults: { flag: false, expiresAt: yesterday, userId: alice.id },
  });
  await db.session.findOrCreate({
    where: { token: "token_bob_1" },
    defaults: { flag: true, expiresAt: tomorrow, userId: bob.id },
  });
  await db.session.findOrCreate({
    where: { token: "token_charlie_1" },
    defaults: { flag: false, expiresAt: yesterday, userId: charlie.id },
  });

  // 5. Logs
  await db.log.bulkCreate([
    {
      level: "INFO",
      message: "User Alice logged in securely",
      userId: alice.id,
    },
    {
      level: "ERROR",
      message: "Failed login attempt for Alice",
      userId: alice.id,
    },
    {
      level: "WARN",
      message: "Bob tried to access unauthorized page",
      userId: bob.id,
    },
    { level: "INFO", message: "Bob updated profile", userId: bob.id },
    { level: "ERROR", message: "Database connection timeout", userId: null }, // System level log
    { level: "INFO", message: "Charlie logged out", userId: charlie.id },
    { level: "INFO", message: "Diana viewed dashboard", userId: diana.id },
  ]);

  console.log("✅ Seed data inserted successfully.");
};

const RUN_QUERIES = async () => {
  const ai = db.ai;

  const prompts = [
    // 1. Complex JOIN + Filtering (User, Roles)
    "Give me the names and emails of all users who have the 'admin' role.",

    // 2. Complex JOIN + Negative Filtering (User, Roles)
    "List all users who do NOT have the 'user' role.",

    // 3. Multi-table JOIN + Aggregation (User, Sessions)
    "How many active sessions does Alice Smith have?",

    // 4. Time-based queries (Sessions)
    "Find all users who have a session that has already expired.",

    // 5. Deep associations + Aggregation (User, Logs)
    "Count the total number of 'ERROR' level logs generated by users who have a verified email.",

    // 6. Multi-table grouping (Logs, Users, Roles)
    "Get all log messages generated by people with the 'manager' role.",

    // 7. Case-insensitive text searching + Associations (Logs, Users)
    "Find all log messages containing the word 'login' (case-insensitive) along with the username of the person who generated them.",

    // 8. Chained/Multiple queries on one line
    "Give me the total count of all users, and also find the username of the person who owns the session token 'token_bob_1'.",

    // 9. Searching by relational absence (Logs, Roles)
    "Show me all system-level logs (where userId is null).",

    // 10. Multi-level nested includes (User -> Roles, User -> Sessions, User -> Logs)
    "Find the user 'dianaprince', and include all her roles, her sessions, and her logs.",
  ];

  console.log("\n🚀 Running 10 complex AI queries...\n");

  for (let i = 0; i < prompts.length; i++) {
    console.log(`\n======================================================`);
    console.log(`🧠 PROMPT ${i + 1}: "${prompts[i]}"`);
    console.log(`======================================================`);
    try {
      const result = await ai.ask(prompts[i]);
      console.log(JSON.stringify(result, null, 2));
    } catch (err) {
      console.error(`❌ ERROR:`, err.message);
    }
  }
};

const start = async () => {
  try {
    console.log("--- Connecting to Postgres ---");
    await db.sequelize.authenticate();
    await db.sequelize.sync({ force: true }); // Drop and recreate tables for clean seed

    await SEED_DATA();
    await RUN_QUERIES();
  } catch (err) {
    console.error("Execution failed:", err);
  } finally {
    await db.sequelize.close();
  }
};

start();
