/**
 * Cleans, sanitizes, and validates the raw code string generated by the LLM.
 * Ensures the code is stripped of markdown fences and correctly formatted
 * before sandbox execution.
 *
 * @param {string} code - The raw response from the LLM
 * @returns {string} The normalized and validated JavaScript expression string
 * @throws {Error} If the generated code format is structurally invalid
 */
function validateGeneratedCode(code) {
  const stripped = code
    .trim()
    // Strip backtick fences: ```js, ```javascript, ``` etc.
    .replace(/^```[\w]*\n?/, "")
    .replace(/```$/, "")
    // Strip tilde fences: ~~~js, ~~~ etc.
    .replace(/^~~~[\w]*\n?/, "")
    .replace(/~~~$/, "")
    .trim();

  // Normalize multi-query: LLM sometimes puts each expression on a new line
  const normalized = stripped
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean)
    .join(", ");

  if (!normalized.startsWith("await dbQuery.applySyncPromise(")) {
    throw new Error(`Unexpected generated code format: "${normalized}"`);
  }

  return normalized;
}

module.exports = validateGeneratedCode;
