/**
 * Cleans, sanitizes, and validates the raw code string generated by the LLM.
 * Ensures the code is stripped of markdown and correctly formatted before sandbox execution.
 *
 * @param {string} code - The raw response from the LLM
 * @returns {string} The normalized and validated JavaScript expression string
 * @throws {Error} If the generated code format is structurally invalid
 */
module.exports = (code) => {
  const stripped = code
    .trim()
    .replace(/^```[\w]*\n?/, "")
    .replace(/```$/, "")
    .trim();

  // Normalize multi-query: LLM sometimes puts each expression on a new line
  const normalized = stripped
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean)
    .join(", ");

  if (!normalized.startsWith("await dbQuery.applySyncPromise(")) {
    throw new Error(`Unexpected generated code format: "${normalized}"`);
  }

  return normalized;
};
